### PR TITLE
use contextmanager to do latex parse patch

### PR DESCRIPTION
**Pull request by cocolato**
Optimize code structure, use contextmanager to do latex parse patch.

### CODE REVIEW

**Comment by cocolato** [comment]
Not sure why the change of `eval_latex_input()` would affect the `eval_card` testcase.

**Comment by eagleoflqj** [comment]
This is a known issue, see commit message of 957cffeb92441ce134f6b729dedc384fd2868cd4.
If you run the failing test it can pass, but with a previous one being ran before that it fails.
I spent some time finding the real issue behind it but no luck.
Maybe just upstream the patches and pretend nothing happens?

**Comment by eagleoflqj** [comment]
The correct integration result is
```py
{'content': {'level': [{'step': [{'p': ({'text': 'The integral of '}, {'inline': '\\frac{1}{\\sqrt{1 - x^{2}}}'}, {'text': ' is '}, {'inline': '\\arcsin{\\left(x \\right)}'})}]}, {'step': [{'p': ({'text': 'Add the constant of integration:'},)}, {'p': ({'block': '\\arcsin{\\left(x \\right)}+ \\mathrm{C}'},)}]}]}, 'answer': {'block': '\\arcsin{\\left(x \\right)}+ \\mathrm{C}'}, 'type': 'StepContainer'}
```
The wrong step is
```py
{'content': {'level': [{'step': [{'p': ({'text': 'Let '}, {'inline': 'u = x'}, {'text': ', then '}, {'inline': '\\mathrm{d}u = \\mathrm{d}x'})}, {'p': ({'text': 'Substitute:'},)}, {'p': ({'block': '\\int \\frac{1}{\\sqrt{1 - u^{2}}}\\, \\mathrm{d}u'},)}, {'level': [{'step': [{'p': ({'text': 'The integral of '}, {'inline': '\\frac{1}{\\sqrt{1 - u^{2}}}'}, {'text': ' is '}, {'inline': '\\arcsin{\\left(u \\right)}'})}]}]}, {'p': ({'text': 'Now substitute '}, {'inline': 'u'}, {'text': ' back in:'})}, {'p': ({'block': '\\arcsin{\\left(x \\right)}'},)}]}, {'step': [{'p': ({'text': 'Add the constant of integration:'},)}, {'p': ({'block': '\\arcsin{\\left(x \\right)}+ \\mathrm{C}'},)}]}]}, 'answer': {'block': '\\arcsin{\\left(x \\right)}+ \\mathrm{C}'}, 'type': 'StepContainer'}
```
For some reason there an unnecessary substitution step at first.

**Comment by eagleoflqj** [comment]
I can locate problem in sympy, which is unfortunately written by me:
https://github.com/sympy/sympy/blob/b9af885473ad7e34b5b0826cb424dd26d8934670/sympy/integrals/manualintegrate.py#L507-L510
I shouldn't have using `is` to compare symbols, but I was under the impression that sympy caches `Symbol` with the same assumptions. That is,
```py
>>> Symbol('x') is Symbol('x')
True
```
However when the test fails, I set breakpoint inside `make_inverse_trig`, executing these in debug console showed weird behavior:
```py
>>> symbol * S.One is symbol
True
>>> S.One * symbol is symbol
False
```

**Comment by cocolato** [comment]
I'll do some research after work.

**Comment by eagleoflqj** [comment]
The patch is upstreamed in SymPy 1.12 so closed by https://github.com/eagleoflqj/sympy_beta/commit/c9c04af863d3ea7367d8f8d15ae38d3a33529f65.
Sadly the random failure still exists.

**Pull request closed without merging**
